### ISSUE TITLE
Not able to rotate logs daily

### ISSUE THREAD

**Issue by akhil1500** [iccicci/rotating-file-stream#54] opened 2020-05-12 06:57 UTC
Hello,
Very thanks for this module. It is very useful for me to logs my REST APIs.

However I am facing some issue in rotation job. The logs files are lost after one day. Can any one home me to findout and fix the issue. Below is my code snippet.
```
function formatDate() {
  var d = new Date(),
    month = '' + (d.getMonth() + 1),
    day = '' + d.getDate(),
    year = d.getFullYear();
    hour = d.getHours();

  if (month.length < 2)
    month = '0' + month;
  if (day.length < 2)
    day = '0' + day;
  if (hour.length < 2)
    hour = '0' + hour

  return [year, month, day, hour].join('-');
}

let log_directory = '/../accesslogs/';
if(process.env.NODE_ENV == 'app'){
  log_directory = '/../../accesslogs-app/'
}

let log_date = formatDate()
let accessLogStream = rfs.createStream('access.log', {
  size: "200M",
  interval: "1d",
  path: path.join(__dirname,log_directory,log_date)
})
```
Below are the log directory and files created
```
2020-05-11-14/
    20200512-0000-01-access.log  ->  file-size - 3.5MB
    20200512-0000-02-access.log  ->  file-size - 3.6MB
    20200512-0000-03-access.log  ->  file-size - 3.3MB
    access.log                                 ->   file-size - 3.3MB
```
There should be log file with ```20200511-0000-01-access.log``` file name as i run the project on 2020-05-11. Next when i have a look at the log directory I didn't find the first day logs.

Can you guys help me out to findout the reason and how to fix this issue?

Many thanks.

**Comment by iccicci** [comment] 2020-05-12 07:32
Hi @akhil1500 , thank you for your interest in **rotating-file-stream** .

At a first check I can see two or three problems:

- `log_date` is static, I mean its value is computed only once, before calling `createStream` ; that's why all your files fall under the same directory;
- probably what you want to use is a [filename generator](https://www.npmjs.com/package/rotating-file-stream#filenametime-index) ; the one in this example actually makes fall different files in different directories depending on the time when rotation happens (in the example the directory name changes monthly, feel free to customize it at your choice);
- if you do so, please pay attention to the last **Note** of the same README section since you are using both `size` and `interval` options;
- I suspect logs about 2020-05-11 are in file `20200512-0000-01-access.log` ; can you please check and confirm? If yes probably what you want is [intervalboundary](https://www.npmjs.com/package/rotating-file-stream#intervalboundary) option;

Hope this helps,
iCC

**Comment by akhil1500** [comment] 2020-05-12 08:02
Hi @iccicci , thanks for the quick response.

For fourth checklist from your response, logs about 2020-05-11 are not found anywhere. ```20200512-0000-01-access.log``` file is having 2020-05-12 date's logs.

I request to address these below questions

- Will that filename generator store logs outside of my project directory?
- I would like to store history of my logs to be stored outside of my project. How can i do that?

Many Thanks.

**Comment by akhil1500** [comment] 2020-05-12 12:33
Hello @iccicci ,
Is it possible to store all logs data out side of the project folder?

**Comment by iccicci** [comment] 2020-05-12 12:36
Hi @akhil1500 ,

about yesterday logs it's hard now to say where are gone...
you can write logs where you prefer, since the `path` option starts with `__dirname` I expect they are stored in your project directory.
Filename generator function should just return a filename, you are free to customize it at your choice.

Hope this helps,
iCC

**Comment by akhil1500** [comment] 2020-05-12 12:43
Hello @iccicci ,
Thanks for the reply. 
I am using file generator as mentioned in the documentation. I am trying to log data outside of my project directory. This is working fine as expected. **But after rotation  few directories are getting created in the project directory.** Can you help me to fix this issue? As i said 
earlier I dont want to store any log info in my project directory.

**Comment by iccicci** [comment] 2020-05-12 13:19
Hi @akhil1500 ,

I'm glad to do it, but I need you share your code.

**Comment by akhil1500** [comment] 2020-05-12 13:35
Hello @iccicci ,
Please find my code snippet below.
```
const pad = num => (num > 9 ? "" : "0") + num;
const generator = (time, index) => {
  if (!time) return "file.log";
 
  var month = time.getFullYear() + "" + pad(time.getMonth() + 1);
  var day = pad(time.getDate());
  var hour = pad(time.getHours());
  var minute = pad(time.getMinutes());

  return path.join(__dirname,'/../logs/',`${month}/${month}${day}-${hour}${minute}-${index}-file.log`);
};

let accessLogStream = rfs.createStream(generator(new Date(),0), {
  interval: "3m"
})

app.use(morgan(':date[iso] :method :url :body :headers :remote-addr :req[content-length] - :status :response-time ms - :res[content-length] ', { stream: accessLogStream }));

```
I am just summarizing my requirements. All logs should be stored out side of the project folder. For development purpose i have set interval to "3m". But I should rotate the logs for one day.

I hope this helps.

Many Thanks.

**Comment by iccicci** [comment] 2020-05-12 15:01
Can you please give me some example name of directories you can see created outside `../logs`?
Are you sure there is no other instances of your application running in background with old cfg?

**Comment by akhil1500** [comment] 2020-05-12 15:16
In logs directory 
```
logs/
   202005/
      20200512-2035-0-file.log
```
Inside my project directory
```
20200512-2036-01-/
   home/ubuntu/Desktop/my-project/logs/202005/20200512-2035-0-file.log
20200512-2039-01-/
  home/ubuntu/Desktop/my-project/logs/202005/20200512-2035-0-file.log
20200512-2042-01-
  home/ubuntu/Desktop/my-project/logs/202005/20200512-2035-0-file.log
```
I am using pm2 process manager. For every change I will use ```pm2 reload my-project``` to restart the server.
There are no other instance running in background with the old cfg i think.

**Comment by iccicci** [comment] 2020-05-12 16:01
Hi @akhil1500 ,

change this
```
let accessLogStream = rfs.createStream(generator(new Date(),0), {
  interval: "3m"
})
```

with this
```
let accessLogStream = rfs.createStream(generator, {
  interval: "3m"
})
```

Hope this helps,
iCC

**Comment by akhil1500** [comment] 2020-05-12 16:27
Hello @iccicci ,
That didn't work.
I am getting ```time as null and index as undefined``` in generator function.

**Comment by iccicci** [comment] 2020-05-12 16:46
Yes,
it works as intended.

change
```
if (!time) return "file.log";
```

with
```
if (!time) return path.join(__dirname,'/../logs/', "file.log");
```

Hope this helps.

**Comment by akhil1500** [comment] 2020-05-12 16:55
Hello @iccicci ,
This is not what i expected and that is not even my problem. Try to understand, after log rotation there are some folders creating inside my project.I don't want that behaviour.  
I told you that I would like to store logs outside of my project folder. Let me know if this won't work with **rotating-file-stream**

**Comment by iccicci** [comment] 2020-05-12 17:03
Please try this

```
const pad = num => (num > 9 ? "" : "0") + num;
const generator = (time, index) => {
  if (!time) return "access.log";

  var month = time.getFullYear() + "" + pad(time.getMonth() + 1);
  var day = pad(time.getDate());
  var hour = pad(time.getHours());
  var minute = pad(time.getMinutes());

  return `${month}/${month}${day}-${hour}${minute}-${index}-access.log`;
};

let accessLogStream = rfs.createStream(generator, {
  interval: "3m",
  path: path.join(__dirname,'/../logs/') // or any other directory
})
```

**Comment by akhil1500** [comment] 2020-05-12 17:50
Hello @iccicci ,
This worked for ```3m```. I am checking for ```1d``` rotation. Can you tell me to understand the reason behind this behaviour? What is the problem with the earlier configuration and current configuration?

**Comment by iccicci** [comment] 2020-05-12 17:54
I suggest to check the diff and to try to understand it by yourself.

If it worked with `3m` I'm pretty sure it will work with `1d` as well.

Feel free to report any other problem or close this issue if your problem is solved.

Thank you,
iCC

**Comment by akhil1500** [comment] 2020-05-13 00:31
Hello @iccicci 
It is working for ```1d``` as well. 

Thank you very much.

**Comment by akhil1500** [comment] 2020-05-16 03:53
Dear @iccicci ,
Why does it is not saving logs after rotation?
When I checked **yesterday around 2PM**, the log file size **was around 50 MB**. By the end of the day the file **size to be expected is 100MB or above**. Today morning I checked the log file size. I found out that it **is just 4.1MB**. **What happened to the yesterday's log file**? Is there any way to prevent this behaviour?

**Comment by akhil1500** [comment] 2020-05-16 04:02
Dear @iccicci ,
Please find the below info which might be helpful.

- We are running the same project in two different ports. One will be main server and another will be backup server. We will test the new functionalities in backup server and then switch to main server if every thing working fine.
- Backup server might be reloaded multiple times based on changes.

**Comment by iccicci** [comment] 2020-05-17 11:25
Hi @akhil1500 ,

there can be several reasons behind the experienced behavior, many of them not bound to the logging system.
The main reason why log file is not growing coming to my mind is that the app is writing lesser information to log.

I suggest you to debug your app and find out what it stopped to write.

Honestly I don't know how to help you.
iCC

**Closed by iccicci** 2020-05-17 11:25 UTC

**Comment by akhil1500** [comment] 2020-05-18 03:59
Dear @iccicci ,

The app is writing proper information to log file. Because of this the log file size is around 100MB per day. It is showing proper log data for today. But It is not showing after rotation. I have written same [generator function](https://www.npmjs.com/package/rotating-file-stream#filenametime-index) which is specified in the docs.

However I will try to do something to debug this behavior.

Thanks
