### ISSUE TITLE
Example use of generator fails with "write after end" error.

### ISSUE THREAD

**Issue by ZiCog** [iccicci/rotating-file-stream#17] opened 2017-10-20 09:33 UTC
The example use of a generator function in the documentation fails with "write after end" error:

Simple program to reproduce this is:

```
var rfs    = require('rotating-file-stream');

function pad(num) {
    return (num > 9 ? "" : "0") + num;
}

function generator(time, index) {
    if(! time)
        return "file.log";

    var month  = time.getFullYear() + "" + pad(time.getMonth() + 1);
    var day    = pad(time.getDate());
    var hour   = pad(time.getHours());
    var minute = pad(time.getMinutes());

    return "/storage/" + month + "/" + month +
        day + "-" + hour + minute + "-" + index + "-file.log";
}

var stream = rfs(generator, {
    size:     '1M',
    interval: '30m'
});

setInterval(function () {
    stream.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx');
}, 10);

```

Using node 8.4.0 on Bash on Windows 10.

**Comment by iccicci** [comment] 2017-10-20 10:19
Thank you,
I'll check this ASAP

**Comment by ZiCog** [comment] 2017-10-20 13:42
Forgot to include the error output. sorry:

```
$ node stream-test.js
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:234:12)
    at RotatingFileStream.Writable.write (_stream_writable.js:285:5)
    at Timeout._onTimeout (/mnt/c/cygwin64/home/zicog/fits-ws-server/stream-test.js:27:12)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
$
```

**Comment by iccicci** [comment] 2017-10-20 13:56
Now I'm so busy.

Can you please try to add following at the end of your example script and run it again?

```
stream.on("error", function(err) { console.log("RFS error", err); });
```

**Comment by ZiCog** [comment] 2017-10-20 18:52
Actually I already tried that. It's a whole other can of worms...

For example, if I already have a 'file.log' file existing I immediately get a lot of 'write after end'  errors. Like so:

```
RFS error Error: write after end
    at writeAfterEnd (_stream_writable.js:234:12)
    at RotatingFileStream.Writable.write (_stream_writable.js:285:5)
    at Timeout._onTimeout (/mnt/c/cygwin64/home/zicog/fits-ws-server/stream-test.js:27:12)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)


```
If I do not have a 'file.log' already then the errors start to come when the rotation happens.

Here is my current test code:

```
var rfs    = require('rotating-file-stream');

function pad(num) {
    return (num > 9 ? "" : "0") + num;
}

function generator(time, index) {
    if(! time)
        return "file.log";

    var month  = time.getFullYear() + "" + pad(time.getMonth() + 1);
    var day    = pad(time.getDate());
    var hour   = pad(time.getHours());
    var minute = pad(time.getMinutes());

    return "/storage/" + month + "/" + month +
        day + "-" + hour + minute + "-" + index + "-file.log";
}

var rfs    = require('rotating-file-stream');
var stream = rfs(generator, {
    size:     '1M',
    interval: '30m'
});

setInterval(function () {
    stream.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx');
}, 10);

stream.on("error", function(err) {
    console.log("RFS error", err);
});


```

**Comment by iccicci** [comment] 2017-10-22 15:26
I run your code and the first error I get is:

```
RFS error { Error: EACCES: permission denied, mkdir '/storage'
    at Error (native) errno: -13, code: 'EACCES', syscall: 'mkdir', path: '/storage' }
```

Maybe you have the same problem? Can you try to change
```
    return "/storage/" + month + "/" + month +
        day + "-" + hour + minute + "-" + index + "-file.log";
```
in
```
    return month + day + "-" + hour + minute + "-" + index + "-file.log";
```
and give me some feedback?

**Comment by ZiCog** [comment] 2017-10-22 18:01
Good point. I did not notice it was trying to write some place it is not allowed to.  Making your suggested modification produces the EACCES error as you show.

The issue then, if it is one, is that without the error handler in place the EACCES error is not generated.

This is my latest, failing, test code:
```
let rfs    = require('rotating-file-stream')

function pad(num) {
  return (num > 9 ? "" : "0") + num
}

function generator(time, index) {
  if(! time)
    return "file.log"

  let month  = time.getFullYear() + "" + pad(time.getMonth() + 1)
  let day    = pad(time.getDate())
  let hour   = pad(time.getHours())
  let minute = pad(time.getMinutes())

  return "/storage/" + month + "/" + month + day + "-" + hour + minute + "-" + index + "-file.log"
}

let stream = rfs(generator, {
  size:     '1M',
  interval: '30m',
  compress: 'gzip'
});

setInterval (function () {
  stream.write('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
}, 10)
```
And the result:
```
$ node stream-test-2.js
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:234:12)
    at RotatingFileStream.Writable.write (_stream_writable.js:285:5)
    at Timeout._onTimeout (/mnt/c/cygwin64/home/zicog/fits-ws-server/stream-test-2.js:26:10)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
$
```

**Comment by iccicci** [comment] 2017-10-22 18:56
As per documentation, in case of fatal error the stream is closed as well.
By design a listener for the `error` event is required to be aware of any error.

Anyway I'll do some research in order to make the package throw an `Exception` if no listener are bound to the `error` event.

Thank you for your suggestion

**Comment by mika-fischer** [comment] 2017-10-27 13:55
See https://nodejs.org/dist/latest-v8.x/docs/api/stream.html#stream_errors_while_writing

**Comment by soulmachine** [comment] 2018-01-11 02:02
I have the same issue:

```
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:237:12)
    at RotatingFileStream.Writable.write (_stream_writable.js:289:5)
```

**Comment by iccicci** [comment] 2018-01-11 08:50
Hi @soulmachine ,

did you attached `error` and `warning` event listener? Can I see the code generating the reported error?

**Comment by soulmachine** [comment] 2018-01-16 23:50
```
RFS error Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:237:12)
    at RotatingFileStream.Writable.write (_stream_writable.js:289:5)
    at RotatedFile.write (/Users/frankdai/github/crawlers/gdax/src/writer/rotated_file.ts:38:17)
    at FileMsgWriter.write (/Users/frankdai/github/crawlers/gdax/src/writer/file_msg_writer.ts:13:22)
    at /Users/frankdai/github/crawlers/gdax/src/crawler/gdax_crawler.ts:178:40
    at Array.forEach (<anonymous>)
    at GdaxCrawler.saveMsg (/Users/frankdai/github/crawlers/gdax/src/crawler/gdax_crawler.ts:178:15)
```

It seems this error only occurs at first time, if I run it again, it won't happen ever.

I think the reason is that first time  the root directory does NOT exist yet, but second time the root directory is created then it will run without error.

**Comment by iccicci** [comment] 2018-01-17 12:56
It seems you missed the **Note:** after this paragraph:
https://www.npmjs.com/package/rotating-file-stream#function-filenameindex

**Comment by soulmachine** [comment] 2018-01-19 08:49
The following is my Typescript code, could you take a look?

```typescript
import rfs = require("rotating-file-stream")
import * as stream from "stream"

export default class RotatedFile {
  private static pad(num: number): string {
    return (num > 9 ? "" : "0") + num
  }

  private static generator(time: Date, index: number) {
    if (!time) {
      return "file.log"
    }

    const month = time.getFullYear() + RotatedFile.pad(time.getMonth() + 1)
    const day = RotatedFile.pad(time.getDate())
    const hour = RotatedFile.pad(time.getHours())
    const minute = RotatedFile.pad(time.getMinutes())

    return month + day + "/" + month + day + "-" + hour + minute + "-" + index + ".json.gz"
  }

  private rootDir: string
  private stream: stream.Writable

  constructor(rootDir: string) {
    this.rootDir = rootDir
    this.stream = rfs(RotatedFile.generator, {
      compress: "gzip",
      interval: "1d", // rotate daily
      path: rootDir,
      size: "256M" // rotate every 256 MegaBytes written
    })
  }

  public write(data: string): void {
    this.stream.write(data)
  }
}
```

**Comment by electrotype** [comment] 2018-04-23 18:33
I have the same error, on Windows 10.
I can't always reproduce the error, but it always happens when I start my application. The `path` where the logs are written already exists.

```
[14:23:57] Error: write after end                                                                                                                                                                                                           
    at writeAfterEnd (_stream_writable.js:236:12)                                                                                                                                                                                           
    at RotatingFileStream.Writable.write (_stream_writable.js:287:5)                                                                                                                                                                        
    at Object.write (C:\_julien\dev\xxx\node_modules\pino-multi-stream\multistream.js:58:16)                                                                                                                
    at EventEmitter.pinoWrite (C:\_julien\dev\xxx\node_modules\pino\pino.js:220:12)                                                                                                                         
    at EventEmitter.LOG (C:\_julien\dev\xxx\node_modules\pino\lib\tools.js:93:10)     
```

Let me know if you want me to test something. Thanks.

**Comment by iccicci** [comment] 2018-04-24 08:03
HI @electrotype , can you show me your code plz?

**Comment by iccicci** [comment] 2018-04-25 20:27
I suggest to try this in order to check if is there an error (which closes the stream).

```javascript
const rotatingFileStream = require('rotating-file-stream');
const rfs = rotatingFileStream('application.log', {
      path: getLogDirPath(loggerConfig),
      size: loggerConfig.getLogRotateThresholdMB() + 'M',
      maxSize: loggerConfig.getLogRotateMaxTotalSizeMB() + 'M',
      maxFiles: loggerConfig.getLogRotateFilesNbr()
    });

rfs.on("error", (err) => {
  console.log("RFS error", err);
});

rfs.on("warning", (err) => {
  console.log("RFS warning", err);
});

if (loggerConfig.isLogToFile()) {
  streams.push({
    level: loggerConfig.getLogLevel(),
    stream: rfs
  });
}
```

**Comment by electrotype** [comment] 2018-04-26 15:03
So here's the error I get!

```
Rotating File Stream error:  { Error: EEXIST: file already exists, mkdir 'C:\_julien\dev\mtl\xxxxnode-api\log'                                                                                                           
  errno: -4075,                                                                                                                                                                                                                             
  code: 'EEXIST',                                                                                                                                                                                                                           
  syscall: 'mkdir',                                                                                                                                                                                                                         
  path: 'C:\\_julien\\dev\\mtl\\xxxxnode-api\\log' }                                                                                                                                                                     
Rotating File Stream error:  { Error: EEXIST: file already exists, mkdir 'C:\_julien\dev\mtl\xxxxnode-api\log'                                                                                                           
  errno: -4075,                                                                                                                                                                                                                             
  code: 'EEXIST',                                                                                                                                                                                                                           
  syscall: 'mkdir',                                                                                                                                                                                                                         
  path: 'C:\\_julien\\dev\\mtl\\xxxxnode-api\\log' }                                                                                                                                                                     
Rotating File Stream error:  { Error: EEXIST: file already exists, mkdir 'C:\_julien\dev\mtl\xxxxnode-api\log'                                                                                                           
  errno: -4075,                                                                                                                                                                                                                             
  code: 'EEXIST',                                                                                                                                                                                                                           
  syscall: 'mkdir',                                                                                                                                                                                                                         
  path: 'C:\\_julien\\dev\\mtl\\xxxxnode-api\\log' }                                                                                                                                                                     
Rotating File Stream error:  { Error: EEXIST: file already exists, mkdir 'C:\_julien\dev\mtl\xxxxnode-api\log'                                                                                                           
  errno: -4075,                                                                                                                                                                                                                             
  code: 'EEXIST',                                                                                                                                                                                                                           
  syscall: 'mkdir',                                                                                                                                                                                                                         
  path: 'C:\\_julien\\dev\\mtl\\xxxxnode-api\\log' }  

The `log` directory indeen already exist! I guess the problem is that RFS triws to create it anyway, in some situations...
```

**Comment by iccicci** [comment] 2018-04-29 21:45
Yes @electrotype , RFS tries to create paths when it detects they are missing.
I'm afraid you found an unknown bug, I never tested the module under windows...
Last suggestion I can say at the moment is: try to check if the really first error you get is something different from the four in the example you sent.

**Comment by normancarcamo** [comment] 2018-08-17 05:56
Same here, but I get this error when I do my tests using Apache benchmark, example: 
```sh
$ ab -n 1300 192.168.0.10:3000/
```

My rotator file is as follow:
```js
// src/utils/logger/rotator.js

const rfs = require('rotating-file-stream');

function generator(time, index) {
  if (!time) return "logs.log";

  const dateiso = new Date().toISOString();
  const datestr = dateiso.substr(0, 10);
  const timestr = dateiso.substr(11, 8);

  return `${datestr}/${timestr}.log`;
}

const stream = rfs(generator, {
  path: `${process.cwd()}/logs`,
  size: '500K',
  interval: '1d',
  maxFiles: 5,
  initialRotation: true
});

stream.on('error', (err) => {
  console.log('******************************************* ERROR');
  console.error(err);
  console.log('*******************************************');
});

stream.on('open', (filename) => {
  console.log('******************************************* OPEN');
  console.log(filename);
  console.log('*******************************************');
});

stream.on('removed', (filename, number) => {
  console.log('******************************************* REMOVED');
  console.log(filename);
  console.log('*******************************************');
});

stream.on('rotation', () => {
  console.log('ROTATION!!!');
});

stream.on('rotated', (filename) => {
  console.log('******************************************* ROTATED');
  console.log(filename);
  console.log('*******************************************');
});

stream.on('warning', (err) => {
  console.log('******************************************* WARNING');
  console.error(err);
  console.log('*******************************************');
});

// process.stdin.pipe(stream);

process.stdin.on('readable', () => {
  const chunk = process.stdin.read();
  if (chunk !== null) {
    stream.write(chunk);
  };
});
```
And this is the errors:
```sh
******************************************* ERROR
Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at RotatingFileStream.Writable.write (_stream_writable.js:287:5)
    at Socket.process.stdin.on (/xxx/xxx/xxx/src/utils/logger/rotator.js:58:12)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at emitReadable_ (_stream_readable.js:513:10)
    at emitReadable (_stream_readable.js:507:7)
    at addChunk (_stream_readable.js:274:7)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
*******************************************
```

And this is the output:

<img width="232" alt="screen shot 2018-08-16 at 11 48 55 pm" src="https://user-images.githubusercontent.com/2402579/44249932-5f98d380-a1af-11e8-8ee6-5d336e958daf.png">

I think that the buffer needs to be closed before to write again and If I don't send multiple request in a short time seems to work pretty well.

Do you think that I should skip this part of my tests with apache benchmark?

**Comment by iccicci** [comment] 2018-08-17 07:45
Hi @normancarcamo ,

your _generator function_ takes not care neither of parameter `index` nor of parameter `time` (apart from first check).

Please pay attention to the note of this paragraph:
https://www.npmjs.com/package/rotating-file-stream#function-filenametime-index
returned _rotated file name_ **must** be function of both parameters _time_ and _index_.

Hope this helps,
iCC

**Closed** 2019-03-23 07:56 UTC
